workers_dev = true
account_id = "2bcbef515e72375efa7e408eeb8d183a"
name = "tattr"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "tattr"
database_id = "c1edd7fa-93c9-4cf0-99cc-801112ee1eea"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "FILES"
bucket_name = "tattr"

[observability]
enabled = true
